### PR TITLE
Add a collection of beauty fixes

### LINKED ISSUE #127: Website - Homepage TLDR content spacing
## Description

The TLDR section on the homepage matches the designs but the spacing feels a bit inconsistent with the other sections. See images below.

Screenshot from 2019-08-26 12-43-17

Screenshot from 2019-08-26 12-43-36

I think more consistent styling would be nice here. cc @reneegranillo

### PR DESCRIPTION
**Pull request by karolinkas**
## Description

Add a collection of style/copy improvements.

**Changes** 🏗 

* Improve `EtherBanner` paddings / spacing / casing
* Increase size of code image
* Use `GridItem` for `TLDR` section

Also closes #127

### CODE REVIEW

File: src/modules/pages/components/Website/HomePage/EtherBanner/EtherBanner.jsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ import styles from './EtherBanner.module.css';
 const MSG = defineMessages({
   title: {
     id: 'pages.Website.HomePage.EtherBanner.title',
-    defaultMessage: 'Not in the cloud;{br}In the Ether',
+    defaultMessage: 'Not in the Cloud;{br}in the Ether',
```
Comment (ryanchristo) [inline src/modules/pages/components/Website/HomePage/EtherBanner/EtherBanner.jsx:18]: Should "Cloud" be capitalized? :thinking:

File: src/modules/pages/components/Website/HomePage/Products/SlideDevelopers/SlideDevelopers.module.css [hunk 2]
```diff
@@ -8,6 +8,6 @@
 
 .image {
   margin-bottom: 0;
-  max-height: 90%;
+  max-height: 98%;
```
Comment (ryanchristo) [inline src/modules/pages/components/Website/HomePage/Products/SlideDevelopers/SlideDevelopers.module.css:13]: I think @collinvine's request for this to be larger was more along the lines of the code itself being larger rather than increasing the height. I think we need to take another screenshot. :grimacing: I told @reneegranillo that it would be ok to cut off the code wherever we need to as long as `createColony` was included.

@collinvine can you clarify your request?

File: src/modules/pages/components/Website/HomePage/TLDR/TLDR.jsx [hunk 3]
```diff
@@ -4,6 +4,7 @@ import React from 'react';
 import { defineMessages } from 'react-intl';
 
 import Heading from '~core/Heading';
+import GridItem from '~core/GridItem';
```
Comment (ryanchristo) [inline src/modules/pages/components/Website/HomePage/TLDR/TLDR.jsx:7]: Nice reuse of the `GridItem` component now with image optional. :+1:

**Review by ryanchristo — COMMENTED** [review]
Nice work! I like that we are reusing the `GridItem` for the TLDR now. :muscle: 

I'm not entirely sure that we should increase the height of the code snippet image but rather we should make the code easier to read (take a new snapshot with increased font size for the code in the editor).

File: src/modules/pages/components/Website/HomePage/Products/SlideDevelopers/SlideDevelopers.module.css (hunk 2 above)
Comment (ryanchristo) [reply src/modules/pages/components/Website/HomePage/Products/SlideDevelopers/SlideDevelopers.module.css:13]: Maybe one of these might be better?

Screenshot from 2019-08-28 12-48-43

Screenshot from 2019-08-28 12-50-00

Comment (collinvine) [reply src/modules/pages/components/Website/HomePage/Products/SlideDevelopers/SlideDevelopers.module.css:13]: That's right, @ryanchristo. People viewing the website should **easily** be able to read the code.

The included examples are better, but I'd suggest that even they are too small.

Comment (ryanchristo) [reply src/modules/pages/components/Website/HomePage/Products/SlideDevelopers/SlideDevelopers.module.css:13]: Ok. If it gets any bigger, we will cut off the `createColony` step so we will need to be more specific about what we want to show and whether we want it to show usable code.

File: src/modules/pages/components/Website/HomePage/EtherBanner/EtherBanner.jsx (hunk 1 above)
Comment (ceolson01) [reply src/modules/pages/components/Website/HomePage/EtherBanner/EtherBanner.jsx:18]: Aha! [I found this](https://joincolony.slack.com/archives/C610VK03G/p1566491834165900)

**Comment by ceolson01** [comment]
@ryanchristo The image has been updated to use the larger of the two that you provided.

cc @reneegranillo and @collinvine for approval as well

Screen Shot 2019-08-28 at 2 30 32 PM

**Review by ryanchristo — APPROVED** [review]
This looks good to me although @reneegranillo and @collinvine should approve as well. I imagine @reneegranillo might want the screenshot to have the same framing as the dApp screenshot.

Also, I would be happy to update the code snippet that we are showing if anyone wants to weigh in on what we should emphasize. I decided to use the code from colonyJS "Get Started" which seemed like the simplest choice at the time but we can change it if we want to show something specific.

**Comment by collinvine** [comment]
Good by me.
